apiVersion: batch/v1
kind: CronJob
metadata:
  name: invoices-cronjob
spec:
  schedule: "31 15 12 9 *" # At minute 0 past every 3rd hour on day-of-month 12 in September.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: julioc98/winterfell-job-image:latest
            env:
            - name: PROJECT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: project-secret
                  key: PROJECT_PRIVATE_KEY
          restartPolicy: OnFailure
