# This file is an example of how to create a secret in k8s.
# Replace name secret.example.yaml with secret.yaml 
# and replace the value of PROJECT_PRIVATE_KEY with your private key.
apiVersion: v1
kind: Secret
metadata:
  name: project-secret
type: Opaque
data:
  PROJECT_PRIVATE_KEY: #Base64 encoded private key